import { describe, it, expect } from 'vitest'
import { readFileSync, readdirSync } from 'node:fs'
import { resolve, dirname, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

// ── Fitness function: the platform npm scope is de-tenanted ───────────────────
//
//  statdash-platform is the PLATFORM; `geostat` is the FIRST TENANT (apps/geostat,
//  package `national-accounts`). The reusable library packages were renamed from
//  the `@geostat/*` scope to `@statdash/*` so the core does not carry the first
//  tenant's name (first-tenant erosion → ADR platform-structure-rearchitecture,
//  Phase 5; multi-tenant north star ADR-0026).
//
//  This test locks the rename: any reappearance of an `@geostat/` npm scope —
//  in an import specifier, a tsconfig/vite/eslint alias, a package.json dep, a
//  Dockerfile, or docs — fails the build. It is the completeness proof that no
//  reference was missed and the guard that a future edit can't reintroduce it.
//
//  Scope ONLY: we forbid the `@geostat/` SCOPE, never the word "geostat" — the
//  tenant app (apps/geostat), its directory, and kit module ids ("geostat" in
//  geostat.ops.json) are legitimate and must survive.

const here         = dirname(fileURLToPath(import.meta.url))
const platformRoot = resolve(here, '..')

// The forbidden token: the npm scope, not the tenant name.
const FORBIDDEN = '@geostat/'

// Extensions that can carry an import, alias, dependency, or doc reference.
const SCANNED = new Set([
  '.ts', '.tsx', '.js', '.mjs', '.cjs',
  '.json', '.css', '.md',
])
// Extension-less files we still want to scan.
const SCANNED_BASENAMES = new Set(['Dockerfile', '.env.example'])

// Directories that are NOT live platform source and are excluded by design:
//  - node_modules / dist            : build artifacts & deps
//  - .claude/agent-memory           : frozen historical snapshots (ADR/memory)
//  - pnpm-lock.yaml                  : regenerated by `pnpm install`
const SKIP_DIRS  = new Set(['node_modules', 'dist', '.claude', '.git'])
const SKIP_FILES = new Set(['pnpm-lock.yaml'])

function scannable(name: string): boolean {
  if (SCANNED_BASENAMES.has(name)) return true
  const dot = name.lastIndexOf('.')
  if (dot < 0) return false
  return SCANNED.has(name.slice(dot))
}

function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    if (e.isDirectory()) {
      if (SKIP_DIRS.has(e.name)) return []
      return walk(resolve(dir, e.name))
    }
    if (SKIP_FILES.has(e.name)) return []
    if (!scannable(e.name)) return []
    return [resolve(dir, e.name)]
  })
}

// This test file documents the forbidden token, so it must exclude itself.
const SELF = resolve(here, 'no-geostat-scope.fitness.test.ts')

describe('platform npm scope is de-tenanted (no @geostat/* survives)', () => {
  it('contains no @geostat/ scope reference in any live source, config, or doc', () => {
    const offenders: string[] = []
    for (const file of walk(platformRoot)) {
      if (file === SELF) continue
      const src = readFileSync(file, 'utf8')
      if (src.includes(FORBIDDEN)) {
        const rel   = relative(platformRoot, file).split(sep).join('/')
        const lines = src.split('\n')
        lines.forEach((line, i) => {
          if (line.includes(FORBIDDEN)) {
            offenders.push(`${rel}:${i + 1}: ${line.trim()}`)
          }
        })
      }
    }
    expect(offenders).toEqual([])
  })
})
